import React, { ReactNode } from 'react';
import { LaptopOutlined, NotificationOutlined, UserOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Breadcrumb, Layout, Menu, message, theme } from 'antd';
import Image from 'next/image';
import { useRouter } from 'next/router';

import { DownOutlined, SmileOutlined } from '@ant-design/icons';
import { Dropdown, Space, Divider, Button } from 'antd';

// css
import styles from './index.module.css'
import { log } from 'console';
import Head from 'next/head';
import Link from 'next/link';
import { logout } from '@/api/user';


const { Header, Content, Sider } = Layout;
const { useToken } = theme;


const items3 = [
    {
        key: "book",
        label: "图书管理",
  
        children: [
            {
                key: "/book",
                label: "图书列表",
            },
            {
                key: "/book/add",
                
                label: "图书添加",
            }

        ] 
    },
    {
        key: "borrow",
        label: "借阅管理",
  
        children: [
            {
                key: "/borrow",
                label: "借阅列表",
            },
            {
                key: "/borrow/add",
                label: "借阅添加",
            }

        ] 
    },
    {
        key: "category",
        label: "分类管理",
  
        children: [
            {
                key: "/category",
                label: "分类列表",
            },
            {
                key: "/category/add",
                label: "分类添加",
            }

        ] 
    },
    {
        key: "user",
        label: "用户管理",
  
        children: [
            {
                key: "/user",
                label: "用户列表",
            },
            {
                key: "/user/add",
                label: "用户添加",
            }

        ] 
    }
]





function LayoutView({children}:{children:ReactNode}) {

  const items: MenuProps['items'] = [
    {
      key: '1',
      label: <Link href='/user'>用户中心</Link> 
    },
    {
      key: '2',
      label:<span onClick={async()=>{
        await logout()
        message.success('登出成功！')
        routes.push('/login')
      }}>登出</span>
    }
  ];



  const {
    token: { colorBgContainer },
  } = theme.useToken();
  const routes = useRouter()
  const { token } = useToken();


  const handleMenuClick:MenuProps['onClick'] = ( {key})=>{
    console.log(key);
    routes.push(key)
    
  }
  const activeMenu = routes.pathname;

  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    <Layout>
      <Header className={styles['header']}>
        <Image 
            src='/next.svg' 
            alt='logo'
            className={styles['logo']}
            width={30}
            height={30}
        />
        XX管理系统
        <span className={styles['user']}>
            <Dropdown menu={{ items }}>
                <a onClick={(e) => e.preventDefault()}>
                <Space>
                    个人中心
                    <DownOutlined />
                </Space>
                </a>
            </Dropdown>
        </span>
      </Header>
      <Layout className={styles['setionInner']}>
        <Sider width={200} style={{ background: colorBgContainer }}>
          <Menu
            mode="inline"
            defaultSelectedKeys={['book']}
            defaultOpenKeys={['book']}
            selectedKeys={[activeMenu]}
            style={{ height: '100%', borderRight: 0 }}
            items={items3}
            onClick={handleMenuClick}
          />
        </Sider>
        <Layout className={styles['sectioncentent']}>
          <Content className={styles['content']}>
            {children}
          </Content>
        </Layout>
      </Layout>
    </Layout>
    </>
  );
};

export default LayoutView;